# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_L', models.IntegerField(default=0, verbose_name='左在庫')),
                ('stock_R', models.IntegerField(default=0, verbose_name='右在庫')),
                ('jan_code_L', models.CharField(max_length=255, verbose_name='左JANコード')),
                ('jan_code_R', models.CharField(max_length=255, verbose_name='右JANコード')),
                ('coordinate_X', models.CharField(max_length=255, verbose_name='座標X')),
                ('coordinate_Y', models.CharField(max_length=255, verbose_name='座標Y')),
                ('earnings', models.IntegerField(default=0, verbose_name='売上')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('purchase_flag', models.CharField(max_length=255, verbose_name='購入フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Jihanki',
            fields=[
                ('jihanki_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='自動販売機ID')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('coordinate_X', models.CharField(max_length=255, verbose_name='座標X')),
                ('coordinate_Y', models.CharField(max_length=255, verbose_name='座標Y')),
                ('change', models.IntegerField(default=0, verbose_name='お釣り')),
            ],
        ),
        migrations.CreateModel(
            name='JihankiProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='在庫')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('xy', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('a3', 'a3'), ('a4', 'a4'), ('a5', 'a5'), ('a6', 'a6'), ('a7', 'a7'), ('a8', 'a8'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('b5', 'b5'), ('b6', 'b6'), ('b7', 'b7'), ('b8', 'b8'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4'), ('c5', 'c5'), ('c6', 'c6'), ('c7', 'c7'), ('c8', 'c8')], max_length=10, null=True, verbose_name='補充位置')),
                ('jihanki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jihanki.Jihanki')),
            ],
        ),
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_code', models.CharField(max_length=255, verbose_name='JANコード')),
                ('stock', models.IntegerField(default=0, null=True, verbose_name='在庫')),
                ('jihanki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jihanki.Jihanki')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('jan_code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='JANコード')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('maker', models.CharField(max_length=255, verbose_name='メーカー')),
                ('maker_price', models.IntegerField(default=0, verbose_name='メーカー価格')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('age', models.IntegerField(default=0, verbose_name='年齢')),
                ('gen', models.CharField(choices=[('ma', '男'), ('fe', '女')], max_length=30, verbose_name='性別')),
                ('pro', models.CharField(choices=[('ser', '公務員'), ('mana', '経営者・役員'), ('emp', '会社員'), ('selem', '自営業'), ('hou', '専業主婦'), ('par', 'パート・アルバイト'), ('stu', '学生'), ('oth', 'その他')], max_length=30, verbose_name='職業')),
                ('area', models.CharField(max_length=50, verbose_name='都道府県')),
            ],
        ),
        migrations.AddField(
            model_name='jihankiproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jihanki.Product'),
        ),
        migrations.AddField(
            model_name='earnings',
            name='jihanki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jihanki.Jihanki'),
        ),
    ]
