# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihanki', '0003_auto_20180123_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='gen',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=30, verbose_name='性別'),
        ),
    ]
