# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihanki', '0004_auto_20180123_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='jan_code',
            field=models.CharField(max_length=255, null=True, verbose_name='JANコード'),
        ),
    ]
