# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihanki', '0005_earnings_jan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jihanki',
            name='jihanki_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='自動販売機ID'),
        ),
    ]
