# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihanki', '0008_auto_20180125_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='earnings',
            field=models.IntegerField(default=0, null=True, verbose_name='売上'),
        ),
        migrations.AddField(
            model_name='loading',
            name='xy',
            field=models.CharField(max_length=10, null=True, verbose_name='補充位置'),
        ),
    ]
