# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihanki', '0009_auto_20180125_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('お茶', 'お茶'), ('水', '水'), ('炭酸・エナジードリンク', '炭酸・エナジードリンク'), ('コーヒー・乳製品', 'コーヒー・乳製品'), ('果汁・野菜', '果汁・野菜'), ('その他', 'その他')], max_length=255, null=True, verbose_name='カテゴリ'),
        ),
    ]
