# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jihanki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_code', models.CharField(max_length=255, verbose_name='JANコード')),
                ('stock', models.IntegerField(default=0, null=True, verbose_name='在庫')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザID')),
                ('age', models.CharField(max_length=100, verbose_name='年齢')),
                ('gen', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=30, verbose_name='性別')),
                ('pro', models.CharField(choices=[('公務員', '公務員'), ('経営者・役員', '経営者・役員'), ('会社員', '会社員'), ('自営業', '自営業'), ('専業主婦', '専業主婦'), ('パート・アルバイト', 'パート・アルバイト'), ('学生', '学生'), ('その他', 'その他')], max_length=30, verbose_name='職業')),
                ('area', models.CharField(max_length=50, verbose_name='都道府県')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='earnings',
            name='jan_code',
            field=models.CharField(max_length=255, null=True, verbose_name='JANコード'),
        ),
        migrations.AlterField(
            model_name='jihanki',
            name='jihanki_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='自動販売機ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='jan_code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='JANコード'),
        ),
        migrations.AddField(
            model_name='loading',
            name='jihanki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jihanki.Jihanki'),
        ),
    ]
