# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jihanki', '0002_auto_20180124_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnings',
            name='jan_code',
        ),
    ]
